"""
Web3Bridge.py
─────────────
Phase 5 — ZeroMQ Subscriber → Blockchain Transaction Submitter

┌─────────────────────────────────────────────────────────────────────┐
│  ARCHITECTURE                                                       │
│                                                                     │
│  C++ DecisionService                                                │
│      │   ZMQ PUB (tcp://127.0.0.1:5555)                             │
│      │   Topic: "ADAS_EVENT <json>|<hash>"                          │
│      │   Topic: "ADAS_HASH <hash>"                                  │
│      ▼                                                              │
│  Python ZMQ SUB (this script)                                       │
│      │   1. Capture raw JSON from ADAS_EVENT messages               │
│      │   2. Save raw JSON to vehicle_log.txt (forensic log)         │
│      │   3. Extract SHA-256 hash from ADAS_HASH messages            │
│      │   4. Submit hash as bytes32 to ForensicLogger.logEvent()     │
│      ▼                                                              │
│  Hyperledger Besu (IBFT 2.0, 4-node private network)                │
│      │   ForensicLogger smart contract (immutable on-chain record)  │
│      ▼                                                              │
│  Auditor.py (Phase 6 — post-accident verification)                  │
└─────────────────────────────────────────────────────────────────────┘

Configuration:
    - Set environment variables or edit the defaults in Config class.
    - For local dev, start the Besu network:
        cd blockchain/besu-network && docker-compose up -d
    - Deploy the contract:
        cd blockchain/blockchain && npx hardhat run scripts/deploy.js --network besu

Usage:
    python Web3Bridge.py [--endpoint tcp://localhost:5555]
                         [--rpc-url http://127.0.0.1:8545]
                         [--contract 0x...]

Press Ctrl+C to stop.

@author  Mukesh Singh
@date    2026-03-10
"""

import argparse
import hashlib
import json
import logging
import os
import signal
import sys
import time
from dataclasses import dataclass
from typing import Optional

import zmq
from web3 import Web3
from eth_account import Account

# ─────────────────────────────────────────────────────────────────────
#  Logging Configuration
# ─────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)-5s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("Web3Bridge")


# ─────────────────────────────────────────────────────────────────────
#  Configuration
# ─────────────────────────────────────────────────────────────────────

@dataclass
class Config:
    """Runtime configuration — override via env vars or CLI flags."""

    # ZeroMQ endpoint to subscribe to (C++ publisher)
    zmq_endpoint: str = "tcp://localhost:5555"

    # Ethereum JSON-RPC endpoint (Besu node 1)
    rpc_url: str = "http://127.0.0.1:8545"

    # Account private key — pre-funded in the Besu genesis.json.
    # NEVER commit a real private key to version control.
    # Override via ADAS_PRIVATE_KEY environment variable.
    private_key: str = os.getenv(
        "ADAS_PRIVATE_KEY",
        # Default: pre-funded account in Besu genesis.json
        "0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3"
    )

    # Deployed ForensicLogger contract address
    contract_address: Optional[str] = os.getenv("ADAS_CONTRACT_ADDRESS", None)

    # Gas parameters (gasPrice=0 for Besu IBFT 2.0 with min-gas-price=0)
    gas_limit: int = 300_000
    gas_price: int = 1000000000  # <--- FIXED: 1 Gwei to avoid ProviderError
    chain_id: int = 1337  # Besu IBFT 2.0 chain ID (from genesis.json)

    # Vehicle identifier (must match the C++ DecisionService payload)
    vehicle_id: str = "ELC23027"

    # Local forensic log file path (Phase 6 auditing)
    local_log_file: str = "vehicle_log.txt"

    # Maximum number of transaction retries on failure
    max_retries: int = 3

    # Delay between retries (seconds)
    retry_delay: float = 1.0


# ─────────────────────────────────────────────────────────────────────
#  ForensicLogger ABI — matches the gas-optimised ForensicLogger.sol
# ─────────────────────────────────────────────────────────────────────
#
#  Only the functions we need are included here.  The full ABI is
#  generated by `npx hardhat compile` in the artifacts/ directory.
#

FORENSIC_LOGGER_ABI = json.loads("""
[
    {
        "inputs": [
            {
                "internalType": "bytes32",
                "name": "forensicHash",
                "type": "bytes32"
            }
        ],
        "name": "logEvent",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "bytes32",
                "name": "forensicHash",
                "type": "bytes32"
            },
            {
                "internalType": "bytes12",
                "name": "vehicleId",
                "type": "bytes12"
            }
        ],
        "name": "logEvent",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "getLogCount",
        "outputs": [
            {
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "uint256",
                "name": "index",
                "type": "uint256"
            }
        ],
        "name": "getLog",
        "outputs": [
            {
                "internalType": "uint64",
                "name": "timestamp",
                "type": "uint64"
            },
            {
                "internalType": "bytes32",
                "name": "forensicHash",
                "type": "bytes32"
            },
            {
                "internalType": "address",
                "name": "reporter",
                "type": "address"
            },
            {
                "internalType": "bytes12",
                "name": "vehicleId",
                "type": "bytes12"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "bytes32",
                "name": "forensicHash",
                "type": "bytes32"
            }
        ],
        "name": "verifyHash",
        "outputs": [
            {
                "internalType": "bool",
                "name": "",
                "type": "bool"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "anonymous": false,
        "inputs": [
            {
                "indexed": true,
                "internalType": "uint256",
                "name": "timestamp",
                "type": "uint256"
            },
            {
                "indexed": true,
                "internalType": "bytes32",
                "name": "forensicHash",
                "type": "bytes32"
            },
            {
                "indexed": true,
                "internalType": "address",
                "name": "reporter",
                "type": "address"
            },
            {
                "indexed": false,
                "internalType": "bytes12",
                "name": "vehicleId",
                "type": "bytes12"
            }
        ],
        "name": "ForensicHashLogged",
        "type": "event"
    }
]
""")


# ─────────────────────────────────────────────────────────────────────
#  Web3 Bridge — Blockchain Transaction Submission
# ─────────────────────────────────────────────────────────────────────

class Web3Bridge:
    """Connects to a Besu node and submits ADAS hashes on-chain."""

    def __init__(self, config: Config):
        self.cfg = config
        self.w3 = Web3(Web3.HTTPProvider(config.rpc_url))
        self.account = Account.from_key(config.private_key)

        # ── Verify connectivity ──────────────────────────────────────
        if self.w3.is_connected():
            chain_id = self.w3.eth.chain_id
            log.info(f"Connected to {config.rpc_url} (chain_id={chain_id})")
        else:
            log.warning(f"Cannot connect to {config.rpc_url}")

        # ── ForensicLogger contract setup ────────────────────────────
        self.contract = None
        if config.contract_address:
            self.contract = self.w3.eth.contract(
                address=Web3.to_checksum_address(config.contract_address),
                abi=FORENSIC_LOGGER_ABI,
            )
            log.info(f"ForensicLogger contract at {config.contract_address}")
        else:
            log.warning("No contract address set — will sign raw value "
                        "transactions for demo purposes.")
            log.info("Deploy ForensicLogger first:")
            log.info("  cd blockchain/blockchain && npx hardhat run "
                     "scripts/deploy.js --network besu")

        # ── Nonce management ─────────────────────────────────────────
        self.nonce = self.w3.eth.get_transaction_count(self.account.address)
        log.info(f"Sender: {self.account.address}  nonce={self.nonce}")

    # ─── Public API ──────────────────────────────────────────────────

    def submit_hash(self, hex_hash: str) -> Optional[str]:
        """
        Sign and send a transaction containing the ADAS hash.

        Implements retry logic: if a transaction fails (e.g., due to
        a nonce conflict or network hiccup), it retries up to
        max_retries times with exponential backoff.

        Returns the transaction hash hex string, or None on failure.
        """
        for attempt in range(1, self.cfg.max_retries + 1):
            try:
                if self.contract:
                    return self._submit_via_contract(hex_hash)
                else:
                    return self._submit_raw(hex_hash)
            except Exception as exc:
                log.error(f"TX attempt {attempt}/{self.cfg.max_retries} "
                          f"failed: {exc}")
                if attempt < self.cfg.max_retries:
                    delay = self.cfg.retry_delay * (2 ** (attempt - 1))
                    log.info(f"Retrying in {delay:.1f}s...")
                    time.sleep(delay)
                    # Refresh nonce in case of nonce-related failure
                    self.nonce = self.w3.eth.get_transaction_count(
                        self.account.address)
                else:
                    log.error("All retry attempts exhausted.")
                    return None

    # ─── Internal ────────────────────────────────────────────────────

    def _submit_via_contract(self, hex_hash: str) -> str:
        """Call ForensicLogger.logEvent(bytes32) on the deployed contract."""
        hash_bytes = bytes.fromhex(hex_hash)

        # Encode the vehicle ID as bytes12 for the extended logEvent
        vehicle_id_bytes = self.cfg.vehicle_id.encode("utf-8").ljust(12, b'\x00')[:12]

        tx = self.contract.functions.logEvent(
            hash_bytes,
            vehicle_id_bytes
        ).build_transaction({
            "from": self.account.address,
            "nonce": self.nonce,
            "gas": self.cfg.gas_limit,
            "gasPrice": self.cfg.gas_price,
            "chainId": self.cfg.chain_id,
        })
        signed = self.w3.eth.account.sign_transaction(tx, self.cfg.private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        self.nonce += 1
        return tx_hash.hex()

    def _submit_raw(self, hex_hash: str) -> str:
        """
        Fallback for dev without a deployed contract:
        send a zero-value transaction with the hash in the `data` field.
        """
        tx = {
            "nonce": self.nonce,
            "to": self.account.address,
            "value": 0,
            "gas": self.cfg.gas_limit,
            "gasPrice": self.cfg.gas_price,
            "data": bytes.fromhex(hex_hash),
            "chainId": self.cfg.chain_id,
        }
        signed = self.w3.eth.account.sign_transaction(tx, self.cfg.private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        self.nonce += 1
        return tx_hash.hex()


# ─────────────────────────────────────────────────────────────────────
#  Main Loop: ZMQ Subscriber → Web3 Bridge
# ─────────────────────────────────────────────────────────────────────

def run_bridge(config: Config):
    """Subscribe to ZMQ hashes and push each one to the blockchain."""

    # ── ZMQ setup (subscribe to both ADAS_HASH and ADAS_EVENT) ───────
    ctx = zmq.Context()
    sub = ctx.socket(zmq.SUB)
    sub.connect(config.zmq_endpoint)
    sub.setsockopt_string(zmq.SUBSCRIBE, "ADAS_")  # catches HASH + EVENT
    log.info(f"ZMQ SUB connected to {config.zmq_endpoint}")

    # ── Local forensic log (Phase 6 — auditing) ─────────────────────
    log_path = os.path.abspath(config.local_log_file)
    log_file = open(log_path, "a", encoding="utf-8")
    log.info(f"Appending raw JSON to {log_path}")

    # ── Web3 bridge setup ────────────────────────────────────────────
    bridge = Web3Bridge(config)

    # ── Graceful shutdown on Ctrl+C ──────────────────────────────────
    running = True

    def _sig(sig, frame):
        nonlocal running
        log.info("Shutting down...")
        running = False

    signal.signal(signal.SIGINT, _sig)

    tx_count = 0
    start = time.time()
    pending_json: Optional[str] = None

    log.info("Listening for ADAS events...\n")

    while running:
        if sub.poll(500):
            raw = sub.recv_string()

            # ── ADAS_EVENT: capture raw JSON for forensic logging ────
            if raw.startswith("ADAS_EVENT "):
                body = raw[len("ADAS_EVENT "):]
                parts = body.rsplit("|", 1)
                if len(parts) == 2:
                    pending_json = parts[0]  # raw JSON payload

            # ── ADAS_HASH: submit hash to blockchain ─────────────────
            elif raw.startswith("ADAS_HASH "):
                hex_hash = raw[len("ADAS_HASH "):]
                tx_hash = bridge.submit_hash(hex_hash)
                tx_count += 1
                elapsed = time.time() - start
                rate = tx_count / elapsed if elapsed > 0 else 0

                # Write raw JSON to local forensic log
                if pending_json:
                    log_file.write(pending_json + "\n")
                    log_file.flush()
                    pending_json = None

                # <--- FIXED: Removed the [:16] slicing to print full hashes
                if tx_hash:
                    log.info(
                        f"[{tx_count:>5}] hash={hex_hash}  "
                        f"tx={tx_hash}  ({rate:.1f} tx/s)")
                else:
                    log.warning(
                        f"[{tx_count:>5}] hash={hex_hash}  "
                        f"TX FAILED  ({rate:.1f} tx/s)")

    log_file.close()
    sub.close()
    ctx.term()
    log.info(f"Done. Submitted {tx_count} transactions.")
    log.info(f"Local log saved to {log_path}")


# ─────────────────────────────────────────────────────────────────────
#  Entry Point
# ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="ZMQ→Web3 bridge for ADAS blockchain forensic hashes")
    parser.add_argument(
        "--endpoint", default="tcp://localhost:5555",
        help="ZMQ PUB endpoint (default: tcp://localhost:5555)")
    parser.add_argument(
        "--rpc-url", default="http://127.0.0.1:8545",
        help="Ethereum JSON-RPC URL (default: http://127.0.0.1:8545)")
    parser.add_argument(
        "--private-key", default=None,
        help="Hex private key (or set ADAS_PRIVATE_KEY env var)")
    parser.add_argument(
        "--contract", default=None,
        help="Deployed ForensicLogger contract address (optional)")
    parser.add_argument(
        "--log-file", default="vehicle_log.txt",
        help="Local forensic log path (default: vehicle_log.txt)")
    args = parser.parse_args()

    cfg = Config(
        zmq_endpoint=args.endpoint,
        rpc_url=args.rpc_url,
        local_log_file=args.log_file,
    )
    if args.private_key:
        cfg.private_key = args.private_key
    if args.contract:
        cfg.contract_address = args.contract

    run_bridge(cfg)